### PR TITLE
Google Analytics onclick tracking for partners

### PR DESCRIPTION
**Pull request by CosimaLL**
**Goal:** 
Adding Google Analytics Event Tracking on Partners page, to see which partner is clicked the most

**steps**:
click on one of the logos on the new partner page  https://3d.io/partners.html 

**Expected result:** => trigger event in GA
- category: "3dio_partners"
- Action: "click"
- Label: name of the partner eg. "aurelien-martel"

**Code based on** : https://github.com/pugjs/pug/issues/1841
**GA tracking documentation**: https://developers.google.com/analytics/devguides/collection/analyticsjs/events

### CODE REVIEW

**Comment by tomas-polach** [comment]
thx :) please also test this approach in firefox (i've encountered some onclick related restrictions when working on other issues earlier)

**Comment by CosimaLL** [comment]
Tested in https://3d.io/branch/CosimaLL-patch-2/partners.html
I can not click on the partners anymore.

**Comment by CosimaLL** [comment]
It works now in firefox and chrome. But the label is not tracked correctly:
screen shot 2017-09-18 at 13 10 18

**Comment by CosimaLL** [comment]
@AVGP you can merge it to 3d.io. it is working on firefox and chrome on desktop and the event label is now also dependent ont the partner.
screen shot 2017-09-18 at 13 58 43

**Pull request merged**
