### PR TITLE
Update 3d-spaces.md

### PR DESCRIPTION
**Pull request by sjeftijssen**

### CODE REVIEW

**Comment by dburgauer** [comment]
@sjeftijssen thanks for this. Couple of comments: 
- Pls link "website" instead to http://www.3dspaces.com.au/plan-to-3d/
- Link as the first sample project something like this: http://view.3dspaces.com.au/3d/3DS1488 and state as "from 750". I'd like the entry level (sub 4 figures) to be there as well
TX!

**Comment by sjeftijssen** [comment]
@dburgauer Adjusted your comments. Could you have a look and let me know if ok. Thanks

**Comment by dburgauer** [comment]
@sjeftijssen perfect, thanks.
@tomas-polach this is ready for Merge from my point of view.

**Comment by tomas-polach** [comment]
@sjeftijssen good work. thx

**Pull request merged**
