### PR TITLE
Error in Link for 3D Import

### PR DESCRIPTION
**Pull request by CosimaLL**
**steps:**
- go to 3d.io
- in the first text
screen shot 2017-09-18 at 16 34 24
- click on "3D import"

**actual result**: 404 error
screen shot 2017-09-18 at 16 33 25

**expected result**:
arrive at https://3d.io/use-case/virtually-staged-3d-scan.html

### CODE REVIEW

**Comment by AVGP** [comment]
Is the ":" supposed to be there after `href=`? I know it was there before but I think that plays a role in why it's not working

**Comment by CosimaLL** [comment]
true i think that was the problem. I fixed it. please merge and close it.

**Comment by CosimaLL** [comment]
true i think that was the problem. I fixed it.

**Comment by tomas-polach** [comment]
thx for this pull request. there is another bug: ">" in html files in text must be converted to "HTML Number" in this case: "&#62;" - other the browser will try to parse it as a tag resulting an error.

you can find a table for special chars here: http://www.ascii.cl/htmlcodes.htm

i will fix this small typo and merge the PR :)

**Pull request merged**
